---
name: Application
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all applications
  method: GET
  url: "{{baseUrl}}/api/v1/apps"
- name: Create an application
  method: POST
  url: "{{baseUrl}}/api/v1/apps"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      name: bookmark
      label: Sample Bookmark App
      signOnMode: BOOKMARK
      settings:
        app:
          url: https://example.com/bookmark.html
- name: Retrieve an application
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}"
- name: Replace an application
  method: PUT
  url: "{{baseUrl}}/api/v1/apps/{{appId}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      name: bookmark
      label: Sample Bookmark App updated
      signOnMode: BOOKMARK
      settings:
        app:
          requestIntegration: true
          url: https://example.com/bookmark.html
- name: Delete an application
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}"
- name: Activate an application
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/lifecycle/activate"
- name: Deactivate an application
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/lifecycle/deactivate"
