---
name: ApplicationInterclientTrustMappings
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all allowed apps for a target app
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/interclient-allowed-apps"
- name: Create an allowed app mapping for a target app
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/interclient-allowed-apps"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      id: 0oa89ks1irGAcYwXw0g5
- name: Delete an interclient trust mapping
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/interclient-allowed-apps/{{allowedAppId}}"
- name: List all target apps for an allowed app
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/interclient-target-apps"
