---
name: ApplicationSSOCredentialKey
requests:
- name: ApplicationSSOCredentialKey / List all certificate signing requests
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Generate a certificate signing request
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
    Content-Type: application/json
  body:
    type: json
    content: {}
- name: ApplicationSSOCredentialKey / Retrieve a certificate signing request
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Revoke a certificate signing request
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Publish a certificate signing request
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}/lifecycle/publish"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / List all key credentials
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Generate a key credential
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/generate"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Retrieve a key credential
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/{{keyId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationSSOCredentialKey / Clone a key credential
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/{{keyId}}/clone"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
