---
name: ApplicationLogos
requests:
- name: ApplicationLogos / Upload an application logo
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/logo"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
