---
name: ApplicationSSO
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Preview the application SAML metadata
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/sso/saml/metadata"
