---
name: ApplicationUsers
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all application users
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users"
- name: Assign an application user
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      id: 00ud4tVDDXYVKPXKVLCO
      scope: USER
      credentials:
        userName: rae.cloud@example.com
- name: Retrieve an application user
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
- name: Update an application user
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      credentials:
        userName: rae.cloud@example.com
        password:
          value: updatedP@55word
- name: Unassign an application user
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
