---
name: ApplicationPolicies
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Assign an app sign-in policy
  method: PUT
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/policies/{{policyId}}"
