---
name: ApplicationTokens
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all application refresh tokens
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/tokens"
- name: Revoke all application tokens
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/tokens"
- name: Retrieve an application token
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/tokens/{{tokenId}}"
- name: Revoke an application token
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/tokens/{{tokenId}}"
