---
name: ApplicationFeatures
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all features
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/features"
- name: Retrieve a feature
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/features/{{featureName}}"
- name: Update a feature
  method: PUT
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/features/{{featureName}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      create:
        lifecycleCreate:
          status: ENABLED
      update:
        lifecycleDeactivate:
          status: ENABLED
        profile:
          status: ENABLED
        password:
          status: ENABLED
          seed: RANDOM
          change: CHANGE
