---
name: ApplicationUsers
requests:
- name: ApplicationUsers / List all application users
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationUsers / Assign an application user
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
    Content-Type: application/json
  body:
    type: json
    content:
      id: 00ud4tVDDXYVKPXKVLCO
      scope: USER
      credentials:
        userName: rae.cloud@example.com
- name: ApplicationUsers / Retrieve an application user
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
- name: ApplicationUsers / Update an application user
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
    Content-Type: application/json
  body:
    type: json
    content:
      credentials:
        userName: rae.cloud@example.com
        password:
          value: updatedP@55word
- name: ApplicationUsers / Unassign an application user
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/users/{{userId}}"
  headers:
    Authorization: SSWS {{apiToken}}
    Accept: application/json
