---
name: ApplicationSSOCredentialKey
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all certificate signing requests
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs"
- name: Generate a certificate signing request
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs"
  headers:
    Content-Type: application/json
  body:
    type: json
    content: {}
- name: Retrieve a certificate signing request
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}"
- name: Revoke a certificate signing request
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}"
- name: Publish a certificate signing request
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/csrs/{{csrId}}/lifecycle/publish"
- name: List all key credentials
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys"
- name: Generate a key credential
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/generate"
- name: Retrieve a key credential
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/{{keyId}}"
- name: Clone a key credential
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/credentials/keys/{{keyId}}/clone"
