---
name: ApplicationSSOFederatedClaims
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all configured federated claims
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/federated-claims"
- name: Create a federated claim
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/federated-claims"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      name: role
      expression: appuser.entitlements.role
- name: Retrieve a federated claim
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/federated-claims/{{claimId}}"
- name: Replace a federated claim
  method: PUT
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/federated-claims/{{claimId}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      name: readOnly
      expression: appuser.entitlements.readOnly
- name: Delete a federated claim
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/federated-claims/{{claimId}}"
