---
name: ApplicationGrants
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: List all app grants
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/grants"
- name: Grant consent to scope
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/grants"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      issuer: "{yourOktaDomain}"
      scopeId: okta.users.read
- name: Retrieve an app grant
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/grants/{{grantId}}"
- name: Revoke an app grant
  method: DELETE
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/grants/{{grantId}}"
