---
name: ApplicationConnections
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Retrieve the default provisioning connection
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/connections/default"
- name: Update the default provisioning connection
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/connections/default"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      baseUrl: https://scim.zscalerbeta.net/1234567/890/scim
      profile:
        authScheme: TOKEN
        token: 00NgAPZqUVy8cX9ehNzzahEE5b-On9sImTcInvWp-x
- name: Retrieve a JSON Web Key Set (JWKS) for the default provisioning connection
  method: GET
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/connections/default/jwks"
- name: Activate the default provisioning connection
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/connections/default/lifecycle/activate"
- name: Deactivate the default provisioning connection
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appId}}/connections/default/lifecycle/deactivate"
- name: Verify the provisioning connection
  method: POST
  url: "{{baseUrl}}/api/v1/apps/{{appName}}/{{appId}}/oauth2/callback"
