---
name: OktaPersonalSettings
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Replace the Okta Personal admin settings
  method: PUT
  url: "{{baseUrl}}/okta-personal-settings/api/v1/edit-feature"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      enableExportApps: true
      enableEnduserEntryPoints: true
- name: List all blocked email domains
  method: GET
  url: "{{baseUrl}}/okta-personal-settings/api/v1/export-blocklists"
- name: Replace the blocked email domains
  method: PUT
  url: "{{baseUrl}}/okta-personal-settings/api/v1/export-blocklists"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      domains:
      - yahoo.com
      - google.com
