---
name: OktaApplicationSettings
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Retrieve the Okta application settings
  method: GET
  url: "{{baseUrl}}/api/v1/first-party-app-settings/{{appName}}"
- name: Replace the Okta application settings
  method: PUT
  url: "{{baseUrl}}/api/v1/first-party-app-settings/{{appName}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      sessionMaxLifetimeMinutes: 720
      sessionIdleTimeoutMinutes: 15
