---
name: OrgSettingSupport
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Retrieve Okta Aerial consent for your org
  method: GET
  url: "{{baseUrl}}/api/v1/org/privacy/aerial"
- name: Grant Okta Aerial access to your org
  method: POST
  url: "{{baseUrl}}/api/v1/org/privacy/aerial/grant"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      accountId: 0200bs0617vvhv2v675mch1cukp
- name: Revoke Okta Aerial access to your org
  method: POST
  url: "{{baseUrl}}/api/v1/org/privacy/aerial/revoke"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      accountId: 0200bs0617vvhv2v675mch1cukp
- name: Retrieve the Okta Support settings
  method: GET
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport"
- name: List all Okta Support cases
  method: GET
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport/cases"
- name: Update an Okta Support case
  method: PATCH
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport/cases/{{caseNumber}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      impersonation:
        status: ENABLED
- name: Extend Okta Support access
  method: POST
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport/extend"
- name: Grant Okta Support access
  method: POST
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport/grant"
- name: Revoke Okta Support access
  method: POST
  url: "{{baseUrl}}/api/v1/org/privacy/oktaSupport/revoke"
