---
name: RateLimitSettings
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Retrieve the rate limit admin notification settings
  method: GET
  url: "{{baseUrl}}/api/v1/rate-limit-settings/admin-notifications"
- name: Replace the rate limit admin notification settings
  method: PUT
  url: "{{baseUrl}}/api/v1/rate-limit-settings/admin-notifications"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      notificationsEnabled: true
- name: Retrieve the per-client rate limit settings
  method: GET
  url: "{{baseUrl}}/api/v1/rate-limit-settings/per-client"
- name: Replace the per-client rate limit settings
  method: PUT
  url: "{{baseUrl}}/api/v1/rate-limit-settings/per-client"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      defaultMode: ENFORCE
- name: Retrieve the rate limit warning threshold percentage
  method: GET
  url: "{{baseUrl}}/api/v1/rate-limit-settings/warning-threshold"
- name: Replace the rate limit warning threshold percentage
  method: PUT
  url: "{{baseUrl}}/api/v1/rate-limit-settings/warning-threshold"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      warningThreshold: 66
