---
name: Schema
headers:
  Authorization: SSWS {{apiToken}}
  Accept: application/json
requests:
- name: Retrieve the default app user schema for an app
  method: GET
  url: "{{baseUrl}}/api/v1/meta/schemas/apps/{{appId}}/default"
- name: Update the app user profile schema for an app
  method: POST
  url: "{{baseUrl}}/api/v1/meta/schemas/apps/{{appId}}/default"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      definitions:
        custom:
          id: "#custom"
          type: object
          properties:
            salesforceUserName:
              title: Salesforce username
              externalName: salesforceUserName
              description: User's username for Salesforce
              type: string
              required: false
              minLength: 1
              maxLength: 20
          required: []
- name: Retrieve the default group schema
  method: GET
  url: "{{baseUrl}}/api/v1/meta/schemas/group/default"
- name: Update the group profile schema
  method: POST
  url: "{{baseUrl}}/api/v1/meta/schemas/group/default"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      definitions:
        custom:
          id: "#custom"
          type: object
          properties:
            groupContact:
              title: Group administrative contact
              description: Group administrative contact
              type: string
              required: false
              minLength: 1
              maxLength: 20
              permissions:
              - principal: SELF
                action: READ_WRITE
          required: []
- name: List the log stream schemas
  method: GET
  url: "{{baseUrl}}/api/v1/meta/schemas/logStream"
- name: Retrieve the log stream schema for the schema type
  method: GET
  url: "{{baseUrl}}/api/v1/meta/schemas/logStream/{{logStreamType}}"
- name: Retrieve a user schema
  method: GET
  url: "{{baseUrl}}/api/v1/meta/schemas/user/{{schemaId}}"
- name: Update a user schema
  method: POST
  url: "{{baseUrl}}/api/v1/meta/schemas/user/{{schemaId}}"
  headers:
    Content-Type: application/json
  body:
    type: json
    content:
      definitions:
        custom:
          id: "#custom"
          type: object
          properties:
            salesforceUserName:
              title: Salesforce username
              description: User's username for Salesforce
              type: string
              required: false
              minLength: 1
              maxLength: 20
              permissions:
              - principal: SELF
                action: READ_WRITE
          required: []
